 export const POSTS = [
	{
		_id: "1",
		text: "Queen of Hills😍",
		img: "/posts/kodaikanal.jpg",
		user: {
			stdname: "Ashwin",
			profileImg: "/avatars/boy3.png",
			dept: "Csbs",
		},
		comments: [
			{
				_id: "1",
				text: "Nice View",
				user: {
					stdname: "Sriram",
					profileImg: "/avatars/girl1.png",
					dept: "Csbs",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "Form is Temperory Class is Permanent😊",
        img: "/posts/virat.jpg",
		user: {
			stdname: "Abinesh R",
			profileImg: "/avatars/boy2.png",
			dept: "CSBS",
		},
		comments: [
			{
				_id: "1",
				text: "King",
				user: {
					stdname: "Ashwin",
					profileImg: "/avatars/girl2.png",
					dept: "Csbs",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "/posts/boys.jpg",
		user: {
			stdname: "johndoe",
			profileImg: "/avatars/boy3.png",
			dept: "John Doe",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "/posts/dhargh.jpg",
		user: {
			stdname: "johndoe",
			profileImg: "/avatars/boy3.png",
			dept: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					stdname: "janedoe",
					profileImg: "/avatars/girl3.png",
					dept: "Jane Doe",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];



const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		dept: "John Doe",
		stdname: "johndoe",
		profileImg: "/avatars/boy2.png",
	},
	{
		_id: "2",
		dept: "Jane Doe",
		stdname: "janedoe",
		profileImg: "/avatars/girl1.png",
	},
	{
		_id: "3",
		dept: "Bob Doe",
		stdname: "bobdoe",
		profileImg: "/avatars/boy3.png",
	},
	{
		_id: "4",
		dept: "Daisy Doe",
		stdname: "daisydoe",
		profileImg: "/avatars/girl2.png",
	},
];

export default USERS_FOR_RIGHT_PANEL