import mongoose from "mongoose";

const autherSchema = new mongoose.Schema(
    {
        StudentName:
        {
            type:String,
            required:true,
            unique:true,
        },
        UserName:
        {
            type:String,
            required:true,
            unique:true,
        },
        DepartMent:
        {
            type:String,
            required:true
        },
        RegNum:
        {
            type:String,
            required:true,
            unique:true
        },
        Email:
        {
            type:String,
            required:true,
            unique:true
        },
        Password:
        {
            type:String,
            required:true
        },
        Following:
        [
            {
                type:mongoose.Schema.Types.ObjectId,
                ref:"User",
                default:[]
            }
        ],
        Followers:
        [
            {
                type:mongoose.Schema.Types.ObjectId,
                ref:"User",
                default:[]
            }
        ],
        Bio:
        {
            type:String,
            default:""
        },
        link:
        {
            type:String,
            default:"Hiii"
        },
        ProfileImage:
        {
            type:String,
            default:""
        },
        CoverImage:
        {
            type:String,
            default:""
        },
        likedPosts:[{
            type:mongoose.Schema.Types.ObjectId,
            ref:"User"
        }]
    },{timestamps:true}
);

const autherModel = mongoose.model("User",autherSchema);

export default autherModel